@echo off
set "JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-17.0.14.7-hotspot"
cd android
echo Running Async Storage Codegen...
call gradlew.bat :react-native-async-storage_async-storage:generateCodegenArtifactsFromSchema --rerun-tasks
echo Running Worklets Codegen...
call gradlew.bat :react-native-worklets:generateCodegenArtifactsFromSchema --rerun-tasks
echo Running Worklets Core Codegen...
call gradlew.bat :react-native-worklets-core:generateCodegenArtifactsFromSchema --rerun-tasks
echo Running Whisper Codegen...
call gradlew.bat :whisper.rn:generateCodegenArtifactsFromSchema --rerun-tasks
echo Done.
